name: Run Unit Test via Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  
          pip install -r requirements.txt
          pip install -r requirements-test.txt
        
        
        continue-on-error: true
      - name: Test with pytest
        run: |
          coverage run -m pytest  -v -s  tests/current_tests.py
      - name: Generate Coverage Report
        run: |
          coverage report -m